[package]
name = "adbc_host"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8"
arrow = { version = "53", features = ["ffi", "csv"] }
arrow-array = { version = "53", features = ["ffi"] }
arrow-schema = "53"
arrow-data = "53"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"